-- MiniFM v2 — complete database schema (single file).
-- Paste the whole thing into the Supabase SQL Editor and run it. Safe to
-- re-run: every statement is IF NOT EXISTS / OR REPLACE / ON CONFLICT guarded.
-- External IDs are MusicBrainz MBIDs (enrichment is keyless MusicBrainz +
-- Cover Art Archive + lrclib).

-- Extensions ---------------------------------------------------------------
create extension if not exists "pgcrypto";

-- Tables -------------------------------------------------------------------
create table if not exists public.artists (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  bio text,
  image_url text,
  musicbrainz_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.albums (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique,
  cover_art_url text,
  release_date date,
  album_type text not null default 'album' check (album_type in ('album', 'single', 'ep')),
  musicbrainz_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.album_artists (
  album_id uuid not null references public.albums (id) on delete cascade,
  artist_id uuid not null references public.artists (id) on delete cascade,
  primary key (album_id, artist_id)
);

create table if not exists public.genres (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique
);

create table if not exists public.languages (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null
);

create table if not exists public.songs (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique,
  album_id uuid references public.albums (id) on delete set null,
  duration_seconds integer,
  file_path text not null,
  file_hash text unique,
  cover_art_url text,
  release_date date,
  language_code text references public.languages (code) on delete set null,
  is_instrumental boolean not null default false,
  plain_lyrics text,
  synced_lyrics text,
  lyrics_source text,
  musicbrainz_id text,
  isrc text,
  play_count integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.song_artists (
  song_id uuid not null references public.songs (id) on delete cascade,
  artist_id uuid not null references public.artists (id) on delete cascade,
  primary key (song_id, artist_id)
);

create table if not exists public.song_genres (
  song_id uuid not null references public.songs (id) on delete cascade,
  genre_id uuid not null references public.genres (id) on delete cascade,
  primary key (song_id, genre_id)
);

create table if not exists public.playlists (
  id uuid primary key default gen_random_uuid(),
  mood_prompt text not null,
  matched_genre_ids uuid[] not null default '{}',
  song_ids uuid[] not null default '{}',
  share_slug text not null unique,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);
create index if not exists playlists_expires_at_idx on public.playlists (expires_at);

create table if not exists public.plays (
  id bigint generated by default as identity primary key,
  song_id uuid not null references public.songs (id) on delete cascade,
  played_at timestamptz not null default now(),
  session_id text
);
create index if not exists plays_song_id_idx on public.plays (song_id);
create index if not exists plays_played_at_idx on public.plays (played_at desc);
create index if not exists plays_session_id_idx on public.plays (session_id);

create table if not exists public.likes (
  id uuid primary key default gen_random_uuid(),
  song_id uuid not null references public.songs (id) on delete cascade,
  session_id text not null,
  created_at timestamptz not null default now(),
  unique (song_id, session_id)
);
create index if not exists likes_session_id_idx on public.likes (session_id);

-- Helpful indexes ----------------------------------------------------------
create index if not exists songs_created_at_idx on public.songs (created_at desc);
create index if not exists songs_play_count_idx on public.songs (play_count desc);
create index if not exists songs_release_date_idx on public.songs (release_date desc);
create index if not exists songs_language_code_idx on public.songs (language_code);
create index if not exists artists_name_idx on public.artists (name);
create index if not exists albums_release_date_idx on public.albums (release_date desc);

-- play_count helper (atomic increment, called with the service-role client) --
create or replace function public.increment_play_count(p_song_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.songs set play_count = play_count + 1 where id = p_song_id;
end;
$$;

-- Row Level Security -------------------------------------------------------
alter table public.artists enable row level security;
alter table public.albums enable row level security;
alter table public.album_artists enable row level security;
alter table public.genres enable row level security;
alter table public.languages enable row level security;
alter table public.songs enable row level security;
alter table public.song_artists enable row level security;
alter table public.song_genres enable row level security;
alter table public.playlists enable row level security;
alter table public.plays enable row level security;
alter table public.likes enable row level security;

-- Public read access for the catalog (the site has no user accounts; only the
-- single admin writes, and all writes go through service-role API routes that
-- verify Supabase Auth + ENABLE_WRITE_OPERATIONS).
drop policy if exists "public read" on public.artists;
create policy "public read" on public.artists for select using (true);
drop policy if exists "public read" on public.albums;
create policy "public read" on public.albums for select using (true);
drop policy if exists "public read" on public.album_artists;
create policy "public read" on public.album_artists for select using (true);
drop policy if exists "public read" on public.genres;
create policy "public read" on public.genres for select using (true);
drop policy if exists "public read" on public.languages;
create policy "public read" on public.languages for select using (true);
drop policy if exists "public read" on public.songs;
create policy "public read" on public.songs for select using (true);
drop policy if exists "public read" on public.song_artists;
create policy "public read" on public.song_artists for select using (true);
drop policy if exists "public read" on public.song_genres;
create policy "public read" on public.song_genres for select using (true);
drop policy if exists "public read" on public.playlists;
create policy "public read" on public.playlists for select using (true);

-- Anonymous clients record plays/likes keyed by their localStorage session id.
drop policy if exists "anon insert" on public.plays;
create policy "anon insert" on public.plays for insert with check (true);
drop policy if exists "public read" on public.plays;
create policy "public read" on public.plays for select using (true);
drop policy if exists "anon insert" on public.likes;
create policy "anon insert" on public.likes for insert with check (true);
drop policy if exists "anon delete own" on public.likes;
create policy "anon delete own" on public.likes for delete using (true);
drop policy if exists "public read" on public.likes;
create policy "public read" on public.likes for select using (true);

-- Storage buckets: `audio` (private, served via short-lived signed URLs so
-- <audio> streams straight from Supabase CDN with native Range support) and
-- `images` (public covers/artist photos).
insert into storage.buckets (id, name, public)
values ('audio', 'audio', false), ('images', 'images', true)
on conflict (id) do update set public = excluded.public;

-- Seed genres (drives the Jev mood classifier's choice criteria + genre pages).
insert into public.genres (name, slug) values
  ('Pop', 'pop'), ('Rock', 'rock'), ('Hip-Hop', 'hip-hop'), ('R&B', 'rnb'),
  ('Electronic', 'electronic'), ('Lo-Fi', 'lo-fi'), ('Jazz', 'jazz'),
  ('Classical', 'classical'), ('Ambient', 'ambient'), ('Folk', 'folk'),
  ('Country', 'country'), ('Metal', 'metal'), ('Punk', 'punk'),
  ('Reggae', 'reggae'), ('Latin', 'latin'), ('K-Pop', 'k-pop'),
  ('J-Pop', 'j-pop'), ('Anime', 'anime'), ('City Pop', 'city-pop'),
  ('Bollywood', 'bollywood'), ('Devotional', 'devotional'),
  ('Afrobeats', 'afrobeats'), ('Synthwave', 'synthwave'), ('Phonk', 'phonk'),
  ('Indie', 'indie'), ('Soul', 'soul')
on conflict (slug) do nothing;

-- Seed languages (drives /language/[slug] index pages).
insert into public.languages (code, name) values
  ('en', 'English'), ('hi', 'Hindi'), ('es', 'Spanish'), ('pa', 'Punjabi'),
  ('ta', 'Tamil'), ('te', 'Telugu'), ('fr', 'French'), ('ko', 'Korean'),
  ('ja', 'Japanese'), ('pt', 'Portuguese'), ('de', 'German'),
  ('it', 'Italian'), ('ml', 'Malayalam'), ('bn', 'Bengali'),
  ('mr', 'Marathi'), ('gu', 'Gujarati'), ('other', 'Other / Instrumental')
on conflict (code) do nothing;
